### ISSUE TITLE
ImportError: No module named eval_pair_cider

### ISSUE THREAD

**Issue by SeekPoint** [mjhucla/mRNN-CR#6]
rzai@rzai00:~/prj/mRNN-CR/external$ ln -s ../../coco-caption coco-caption
rzai@rzai00:~/prj/mRNN-CR/external$ cd ..
rzai@rzai00:~/prj/mRNN-CR$ PYTHONPATH=../coco-caption python cr_mRNN_demo.py
Traceback (most recent call last):
  File "cr_mRNN_demo.py", line 1, in <module>
    from concensus_reranking_utils.consensus_reranking import Consensus_Reranking
  File "/home/rzai/prj/mRNN-CR/concensus_reranking_utils/consensus_reranking.py", line 21, in <module>
    from pycocoevalcap.eval_pair_cider import COCOEvalCapPairCider
ImportError: No module named eval_pair_cider
rzai@rzai00:~/prj/mRNN-CR$ 
rzai@rzai00:~/prj/mRNN-CR$ 
rzai@rzai00:~/prj/mRNN-CR$ 
rzai@rzai00:~/prj/mRNN-CR$ cd ../coco-caption/
rzai@rzai00:~/prj/coco-caption$ git pull
Already up-to-date.
rzai@rzai00:~/prj/coco-caption$ ll ../coco-caption/
total 740
drwxrwxr-x   7 rzai rzai   4096 12月 14 15:20 ./
drwxrwxr-x 155 rzai rzai  12288 12月 14 15:03 ../
drwxrwxr-x   2 rzai rzai   4096 11月  8 17:24 annotations/
-rw-rw-r--   1 rzai rzai 705388 11月  8 17:24 cocoEvalCapDemo.ipynb
drwxrwxr-x   8 rzai rzai   4096 12月 14 15:22 .git/
-rw-rw-r--   1 rzai rzai      6 11月  8 17:24 .gitignore
-rw-rw-r--   1 rzai rzai   1561 11月  8 17:24 license.txt
drwxrwxr-x   7 rzai rzai   4096 12月 14 15:08 pycocoevalcap/
drwxrwxr-x   2 rzai rzai   4096 12月 14 15:08 pycocotools/
-rw-rw-r--   1 rzai rzai   2091 11月  8 17:24 README.md
drwxrwxr-x   2 rzai rzai   4096 11月  8 17:24 results/
rzai@rzai00:~/prj/coco-caption$

**Comment by SeekPoint** [comment]
fixed by another issue
